apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: poc-accelerator
  labels:
    app: busybox
    deploy: recreate-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  strategy:
    type: Recreate   # 💡 all old pods are killed before new ones are created
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36   # replace with your busybee image if custom
        command: ["sh", "-c", "while true; do echo Hello from BusyBee $(date); sleep 5; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo ready"
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo live"
          initialDelaySeconds: 10
          periodSeconds: 20
      tolerations:
        - effect: NoSchedule
          key: node-role
          operator: Equal
          value: worker
